name: flutter_ui_kit
description: Flutter UI Kit @ Change

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.14.0
  camera: ^0.5.4
  path_provider: ^1.2.0
  flutter_cupertino_date_picker: ^1.0.8
  flutter_sparkline:
    git:
      url: https://github.com/ChangeFinance/flutter_sparkline.git
      ref: add-graph-paint-callback
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^2.0.1
  mockito: ^4.0.0
  package_info: ^0.4.0+3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: CryptoFont
      fonts:
        - asset: lib/fonts/cryptofont-webfont.ttf
          weight: 400
    - family: Circular
      fonts:
        - asset: lib/fonts/CircularPro-Book.ttf
          weight: 400

  assets:
    - assets/update-app.svg
    - assets/euro.svg
    - assets/bitcoin_colourful.svg
    - assets/referral-screen.svg
    - assets/card_holder.svg
    - assets/free_trading.svg
    - assets/fully_regulated.svg
    - assets/macbook_user.svg
    - assets/secure_funds.svg
    - assets/deposit.svg
    - assets/confirmation.svg
    - assets/convert_is_secured.svg
    - lib/assets/icons/
